version: '2'
services:
  savage-dl:
    build: .
    image: savage-dl
    ports:
      - "2001:2001"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"

